{% set name = "docopt.cpp" %}
{% set version = "0.6.3" %}
{% set sha256 = "28af5a0c482c6d508d22b14d588a3b0bd9ff97135f99c2814a5aa3cbff1d6632" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/docopt/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake_install.patch

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/docopt  # [unix]
    - test -f ${PREFIX}/include/docopt/docopt.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/docopt/docopt-config.cmake  # [unix]
    - test -f ${PREFIX}/lib/libdocopt.so  # [linux]
    - test -f ${PREFIX}/lib/libdocopt.dylib  # [osx]
    - if exist %LIBRARY_PREFIX%\include\docopt\docopt.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\docopt-config.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\lib\docopt.dll  # [win]

about:
  home: https://github.com/docopt/docopt.cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: docopt creates beautiful command-line interfaces
  description: |
    This is a port of the docopt.py module (https://github.com/docopt/docopt), and we have tried to
    maintain full feature parity (and code structure) as the original.
  doc_url: https://github.com/docopt/docopt.cpp
  dev_url: https://github.com/docopt/docopt.cpp

extra:
  recipe-maintainers:
    - tdegeus
